#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FIXTURE="$ROOT_DIR/tests/fixtures/elliptic/spectral_two_puncture_hamiltonian_3d.tn"
OUTPUT_PATH="${1:-/tmp/tensorium_qc0_bssn_slice.csv}"
PRECONDITIONER="${TP_PRECONDITIONER:-${TENSORIUM_INITIAL_DATA_PRECONDITIONER:-mapped_fd_multigrid}}"
PRECONDITIONER_SWEEPS="${TP_PRECONDITIONER_SWEEPS:-${TENSORIUM_INITIAL_DATA_PRECONDITIONER_SWEEPS:-}}"
SPECTRAL_RESOLUTION="${TP_RESOLUTION:-${TENSORIUM_INITIAL_DATA_RESOLUTION:-}}"

TENSORIUM_SLICE_N="${TP_SLICE_N:-${TENSORIUM_SLICE_N:-129}}" \
TENSORIUM_HALF_WIDTH="${TP_HALF_WIDTH:-${TENSORIUM_HALF_WIDTH:-8.0}}" \
TENSORIUM_INITIAL_DATA_PRECONDITIONER="$PRECONDITIONER" \
TENSORIUM_INITIAL_DATA_PRECONDITIONER_SWEEPS="$PRECONDITIONER_SWEEPS" \
TENSORIUM_INITIAL_DATA_RESOLUTION="$SPECTRAL_RESOLUTION" \
  "$ROOT_DIR/run_initial_data.sh" "$FIXTURE" "$OUTPUT_PATH"
